# Generated by Django 5.0.2 on 2024-04-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cards')),
            ],
        ),
    ]
